sudo: false
language: perl
perl:
   - '5.10'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - rm .travis.yml
   - export AUTHOR_TESTING=0
   - sudo apt-get install -y libarchive-any-lite-perl libarchive-zip-perl libmodule-cpants-analyse-perl libtest-kwalitee-perl
   - cpanm Dist::Zilla::Plugin::Test::Kwalitee::Extra
install:
   - cpanm --installdeps --verbose  .
