sudo: false
language: perl
perl:
   - 'blead'
   - '5.20'
   - '5.18'
   - '5.16'
   - '5.14'
   - '5.12'
   - '5.10'
   - '5.8'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - rm .travis.yml
   - export AUTHOR_TESTING=0
   - cpanm Dist::Zilla::Plugin::Test::Kwalitee::Extra
install:
   - cpanm --installdeps --verbose  .
