sudo: true 
language: perl
perl:
   - '5.10'
matrix:
   allow_failures:
      - perl: 'blead'
      - perl: '5.8'
   fast_finish: true
branches:
   only: /^build\/.*/
before_install:
   - rm .travis.yml
   - export AUTHOR_TESTING=0
   - cpanm Archive::Any::Lite
   - cpanm Archive::Zip
   - cpanm Module::CPANTS::Analyse
   - cpanm Test::Kwalitee::Perl 
   - cpanm Dist::Zilla::Plugin::Test::Kwalitee::Extra
install:
   - cpanm --installdeps --verbose  .
